### PR TITLE
Add per-Tab BROKEN threshold Config option

### PR DESCRIPTION
**Pull request by MushuEE**
This will be used to enable per-tab control of what threshold levels will yield a BROKEN tab.

### CODE REVIEW

**Comment by fejta** [comment]
I'd suggest creating an issue and linking the various PRs related here.

ref https://github.com/GoogleCloudPlatform/testgrid/pull/129


Thoughts on waiting until something uses these to check them in?

**Comment by michelle192837** [comment]
I think we can wait until something uses them, yeah. ^^ Should be safe to include with a change like that.

The other thing is that until the config.proto in this repo is source-of-truth, we need to replicate this change internally first. (That's what the `hold` earlier was.)

**Comment by michelle192837** [comment]
Ah, and linking an issue is just mentioning `#<issue num>` in the comments, like Erick did above with 129.

**Comment by fejta** [comment]
If you paste a link to a github issue X (even from another org) in github issue Y it will create a reference between them (aka you can click on the link to Y in issue X and github will automatically create a reference in Y to note that X refers to it -- for example: https://github.com/GoogleCloudPlatform/testgrid/issues/26#ref-pullrequest-504317659)

**Comment by MushuEE** [comment]
Now used for #133 however I think we need #132 to go in first and I need to make this change in sync with internal

**Comment by MushuEE** [comment]
Pulled in with #132

**Pull request closed without merging**
