### PR TITLE
Change gcs_prefix back to query for consistency.

### PR DESCRIPTION
**Pull request by michelle192837**
This will be followed up with a PR in test-infra to change uses of gcs_prefix to query.

Needed so we can validate all types of config protos.

### CODE REVIEW

**Comment by fejta** [comment]
I'm not a fan. GCSPrefix is the right name.

**Comment by michelle192837** [comment]
It doesn't work for the internal instance, and it's going to require extensive patching to be able to use this internally with the field change. I'd really like to get us using the same config.proto internally and externally.

**Comment by fejta** [comment]
We can use a different name internally

**Comment by chases2** [comment]
I'd like to do a bit of research before weighing in here.
/hold

**Pull request closed without merging**
