### PR TITLE
Update testgrid's bazel and cloud.google.com/go dependencies

### PR DESCRIPTION
**Pull request by spiffxp**
I tried upgrading the cloud dependency but was unable to get bazel to work with it unless I upgraded to bazel 2.2.0.  For grins I tried bumping to 3.0.0 locally and had no problems.

Getting this to pass in CI will be more involved though. I was thinking about following the same dance we do for kubernetes/test-infra (ref: https://github.com/kubernetes/test-infra/tree/master/images#updating-test-infra-images) which would require making a testgrid-specific dual-bazel-version image and updating jobs accordingly.

I wanted to get eyes on this PR before going through that

### CODE REVIEW

**Comment by spiffxp** [comment]
Supercedes https://github.com/GoogleCloudPlatform/testgrid/pull/90

**Comment by spiffxp** [comment]
OK, looks like CI is happy with bazel 3.0.0 and the `cloud.google.com/go` -> `cloud.google.com/go/storage` change

**Comment by fejta** [comment]
weird and great!

**Pull request merged**
