### PR TITLE
Add npm presubmit job.

### LINKED ISSUE #1178: Add npm test as a presubmit
Missed an issue with a recent PR that should've been caught if npm test was run as part of the presubmits (see #1175)

/assign

### PR DESCRIPTION
**Pull request by michelle192837**
Kinda jank, but this does successfully run the presubmits.

Forces running on Playwright and uses one of their available images (see https://playwright.dev/docs/ci).

Fixes #1178

/hold

### CODE REVIEW

**Review by chases2 — APPROVED** [review]
Looks good! Thanks so much. Unhold when you're ready. :D

**Comment by bweston92** [comment]
Would it be possible to pass the Docker flag for `--ipc=host` or is that a risk?

> Using --ipc=host is also recommended when using Chromium—without it Chromium can run out of memory and crash

https://playwright.dev/docs/ci#docker

**Comment by michelle192837** [comment]
> Would it be possible to pass the Docker flag for `--ipc=host` or is that a risk? Apparently helps with Chromium not running out of memory which make cause flakes.
> 
> > Using --ipc=host is also recommended when using Chromium—without it Chromium can run out of memory and crash
> 
> https://playwright.dev/docs/ci#docker

Good point! I don't think it's a significant risk, but just in case I'm going to leave it off for now, and add it if we see issues with this in presubmit. Thanks!

**Pull request merged**
