### PR TITLE
Add ResultStore search to Updater.

### PR DESCRIPTION
**Pull request by michelle192837**
Initial commit that adds some logic and basic unit tests for these functions.

Will follow up with further changes once I verify this works against a real API.

### CODE REVIEW

**Comment by michelle192837** [comment]
/assign @chases2 @sultan-duisenbay 

I know this is a long change (apologies!), let me know if I can break it up for easier reviewing. ^^

**Review by sultan-duisenbay — APPROVED** [review]
LGTM with couple of nits and questions!

/hold

**Pull request merged**
