### PR TITLE
Update test status severity.

### PR DESCRIPTION
**Pull request by michelle192837**

### CODE REVIEW

**Comment by e-blackwelder** [comment]
I see that the statusSeverity is being sorted differently. Are the "enum" values being defined, used, or stored elsewhere? (In a previous job, I noticed an API's enum values being changed overtime, resulting in client-side bugs. I'm worried that something similar might be happening here as well.)

**Comment by michelle192837** [comment]
Severity is specifically to avoid remapping enum values; we keep a separate map of 'this status should show up over this other status' to keep it separate from the defined enum in the proto.

**Comment by michelle192837** [comment]
To be clear, the updated status severity sorting is intentional, this should make things more consistent between parts of TestGrid.

**Review by e-blackwelder — APPROVED** [review]

**Pull request merged**
