### PR TITLE
Update cloud.google.com/go dependency to use new storage package

### PR DESCRIPTION
**Pull request by saschagrunert**
Hey, we would like to update our golang dependencies in in https://github.com/kubernetes/release/pull/1067, but for that we would need to update the cloud.google.com/go package here which has been split into a dedicated `storage` package.

### CODE REVIEW

**Comment by saschagrunert** [comment]
@michelle192837 may I ask you what I can do to fix that build issue? :innocent:

**Comment by michelle192837** [comment]
Not sure what's up, but are you sure that swapping to the new dependency doesn't require any code changes? Does `bazel test //...` work locally for you?

**Comment by chases2** [comment]
I'm getting compilation issues when I try and run tests against this change.

```
/b/f/w/external/com_google_cloud_go_storage/bucket.go:532:30: b.LocationType undefined (type *storage.Bucket has no field or method LocationType)
```
```
/b/f/w/external/com_google_cloud_go_storage/bucket.go:560:4: unknown field 'UniformBucketLevelAccess' in struct literal of type storage.BucketIamConfiguration
```

Maybe changing this import requires a change in the `import` line in the go code itself?

**Comment by saschagrunert** [comment]
Hm usually there should not be a need for further path modification. It seems strange to me that it builds with a simple `go test ./...` but not via bazel :man_shrugging:

**Comment by michelle192837** [comment]
Iiii really have no idea what's going on here. :/

/cc @fejta 

Erick, anything obvious missing here? `./hack/update-all.sh` and `bazel run @io_k8s_repo_infra//hack:update-bazel` seem to run clean?

**Comment by fejta** [comment]
Did you run `@io_k8s_repo_infra//hack:update-deps`?

Perhaps other dependencies are still using `com_google_cloud_go//storage:go_default_library`?

**Comment by saschagrunert** [comment]
> Did you run `@io_k8s_repo_infra//hack:update-deps`?

Yes, this does not modify any local content.
 
> Perhaps other dependencies are still using `com_google_cloud_go//storage:go_default_library`?

Hm, I'm not sure but I would not expect that. :thinking:

**Comment by justaugustus** [comment]
Needs rebase.

**Comment by spiffxp** [comment]
/close
Superseded by https://github.com/GoogleCloudPlatform/testgrid/pull/141

**Comment by spiffxp** [comment]
/close
hm, does the prow on this repo not let me close, or was this a dropped webhook?

**Comment by saschagrunert** [comment]
I’ll close, thanks 😊

**Pull request closed without merging**
